name: update coco keys

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  updateKeys:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - uses: actions/cache@v3
        with:
          path: |
            ~/.local/lib/python3.8/site-packages
            ./node_modules
            ~/.cache/puppeteer
          key: ${{ runner.os }}-autoCI-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-autoCI-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/package.json') }}

      - name: install Dependences
        run: |
          npm install
          # pip install -r requirements.txt

      - name: extra keys
        run: |
          source $GITHUB_WORKSPACE/coco/coco.sh
          main

      - name: push changes to cocokeys branch
        run: |
          mkdir cocokeys
          mv coco_keys.json ./cocokeys
          cd cocokeys
          git init -b cocokeys
          git add .
          git commit -m "update coco keys at $(date "+%Y/%m/%d %H:%M")"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin cocokeys


      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 6
